[tool.black]
target-version = ['py37']
# Keep exclude in sync with flake8 config in tox.ini
exclude = '''
/(
      \.git
    | \.tox
    | node_modules
    | __pycache__
    | \.eggs
    | .*\.egg
    | .*\.egg-info
    | env
    | venv
    | \.venv
    | \.serverless
)/
'''
