name: "Pull Request Labeler"
on:
  pull_request:

jobs:
  triage:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      issues: write
      pull-requests: write

    steps:
    - uses: actions/labeler@5c7539237e04b714afd8ad9b4aed733815b9fab4 # v4.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
